language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
#- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
#- ./src/main/asciidoc/ghpages.sh
script: mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: eO6b1PT+fmGvNVVYa9WqMwr7d6RXOx/S0m51KfgpeflqMkMnhnAcC8hzPRA2vmQN1kqRdr3OjN6bazRYsRxlQOYsev4QzDv74E9CTXLXzVi+L98Oq7BqD6MpEAEfZVWz1lvGUiaGKTghS7Tseag3sK5CslPr2LA0UAZWd0v1GUo=
